import time, os
os.system('title Mail Maker By Qu3ti')
from faker import Faker
fake = Faker()
print("Genera 10 mails randoms.")
idk = input("Apreta una tecla para crearlos...")
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(0.01)
print(fake.email())
time.sleep(100)

